# Generated by Django 5.2.4 on 2025-08-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_diagnostico', '0002_pregunta_alter_episodiocefalea_anticonceptivos_and_more'),
        ('tratamiento', '0002_alter_medicamento_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='episodio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='evaluacion_diagnostico.episodiocefalea', verbose_name='Episodio de Cefalea'),
        ),
    ]
