# Generated by Django 5.2.4 on 2025-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0003_alter_tratamiento_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales del tratamiento', null=True),
        ),
    ]
